### ISSUE TITLE
Tutorial fails on R 3.1.2: non-unique values when setting 'row.names'

### ISSUE THREAD

**Issue by Vili** [rOpenGov/sorvi#3]
> library(sorvi)
> Sys.setlocale(locale="UTF-8") 
> municipality.info.mml <- get_municipality_info_mml()
Loading http://data.okf.fi/ropengov/avoindata/mml/rdata/Yleiskartta-1000/HallintoAlue.RData. (C) MML 2013. Converted to RData shape object by Louhos. For more information, see https://github.com/avoindata/mml/
Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names':

**Comment by antagomir** [comment]
Thanks for reporting ! 

We need to update the CRAN version soon. Meanwhile you can use the devel version. I have now added this also in the sorvi tutorial page (tnx for pointing this out !) and the following works for me out-of-the-box now:

library(devtools)
install_github("ropengov/sorvi")
ibrary(sorvi)
Sys.setlocale(locale="UTF-8")
municipality.info.mml <- get_municipality_info_mml()

sorvi was recently splitted in multiple smaller compact packages, due to these major changes we are still in the process of finalizing it all. This activity certainly helps. Let us know if you bump into any other issues.

**Comment by antagomir** [comment]
Ok, seems to work with the latest CRAN version.
